#!/usr/bin/env python
# -*- coding=utf-8 -*-
import sys

'''
@param 1 状态：START、CONTENT、STOP
@param 2 文件路径
@param 3 内容
'''
if __name__ == '__main__':
    if len(sys.argv) != 4:
        sys.exit(1);
    if sys.argv[1] == 'START':
        with open(sys.argv[2], 'w+') as fw:
            fw.truncate(0)
            fw.write('/* This file is generated by a script, do not compile it */\n')
            fw.write('#ifndef _GLIB_CONFIG_H_\n')
            fw.write('#define _GLIB_CONFIG_H_\n')
            fw.write("\n\n")
    elif sys.argv[1] == 'CONTENT':
        with (open(sys.argv[2], 'a+') as fw):
            str = "#define " + "HAVE_" + sys.argv[3].replace('.', '_').replace('/', '_').replace('-', '_').upper()
            fw.write(str)
            strLen = len(str)
            if strLen < 48:
                spaceNum = 48 - len(str) - 1
                while spaceNum > 0:
                    fw.write(" ")
                    spaceNum -= 1
            else:
                fw.write(" ")
            fw.write("1" + "    // " + sys.argv[3] + "\n")
    elif sys.argv[1] == 'STOP':
        with open(sys.argv[2], 'a+') as fw:
            fw.write("\n\n")
            fw.write('#endif // _GLIB_CONFIG_H_')
    sys.exit(0)
