all : demo1 demo2

dir=$(shell realpath `pwd`)


demo1:
	@echo "cp $(dir)/menu1.desktop /usr/share/deepin/dde-file-manager/oem-menuextensions/"
	@echo "此时鼠标右键可看到添加的菜单项"
	@echo "详情参看：https://developer.chinauos.com/#/pages/document/info?id=ae53aada-100b-498c-ba02-b905fa3cf9ed&admin="


.PHONY:all demo1
