/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    encryptBlock
 * Signature: ([BBJ[BIJ[BI[B[B[I[B[II[BI[B[B[B[BIJ)I
 */
JNIEXPORT jint JNICALL Java_Main_encryptBlock
  (JNIEnv *, jobject, jbyteArray, jbyte, jlong, jbyteArray, jint, jlong, jbyteArray, jint, jbyteArray, jbyteArray, jintArray, jbyteArray, jintArray, jint, jbyteArray, jint, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
