[tool.poetry]
name = "lang-chain"
version = "0.1.0"
description = ""
authors = ["丁敬 <dingjing@live.cn>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.8"
langchain = "^0.3.0"
jupyter = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
