// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: msg.proto
#ifndef GRPC_msg_2eproto__INCLUDED
#define GRPC_msg_2eproto__INCLUDED

#include "msg.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

class MsgService final {
 public:
  static constexpr char const* service_full_name() {
    return "MsgService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetMsg(::grpc::ClientContext* context, const ::MsgRequest& request, ::MsgResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MsgResponse>> AsyncGetMsg(::grpc::ClientContext* context, const ::MsgRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MsgResponse>>(AsyncGetMsgRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MsgResponse>> PrepareAsyncGetMsg(::grpc::ClientContext* context, const ::MsgRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MsgResponse>>(PrepareAsyncGetMsgRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetMsg(::grpc::ClientContext* context, const ::MsgRequest* request, ::MsgResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetMsg(::grpc::ClientContext* context, const ::MsgRequest* request, ::MsgResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MsgResponse>* AsyncGetMsgRaw(::grpc::ClientContext* context, const ::MsgRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MsgResponse>* PrepareAsyncGetMsgRaw(::grpc::ClientContext* context, const ::MsgRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetMsg(::grpc::ClientContext* context, const ::MsgRequest& request, ::MsgResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MsgResponse>> AsyncGetMsg(::grpc::ClientContext* context, const ::MsgRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MsgResponse>>(AsyncGetMsgRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MsgResponse>> PrepareAsyncGetMsg(::grpc::ClientContext* context, const ::MsgRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MsgResponse>>(PrepareAsyncGetMsgRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetMsg(::grpc::ClientContext* context, const ::MsgRequest* request, ::MsgResponse* response, std::function<void(::grpc::Status)>) override;
      void GetMsg(::grpc::ClientContext* context, const ::MsgRequest* request, ::MsgResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::MsgResponse>* AsyncGetMsgRaw(::grpc::ClientContext* context, const ::MsgRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::MsgResponse>* PrepareAsyncGetMsgRaw(::grpc::ClientContext* context, const ::MsgRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetMsg_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetMsg(::grpc::ServerContext* context, const ::MsgRequest* request, ::MsgResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetMsg() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMsg(::grpc::ServerContext* /*context*/, const ::MsgRequest* /*request*/, ::MsgResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetMsg(::grpc::ServerContext* context, ::MsgRequest* request, ::grpc::ServerAsyncResponseWriter< ::MsgResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetMsg<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetMsg() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::MsgRequest, ::MsgResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::MsgRequest* request, ::MsgResponse* response) { return this->GetMsg(context, request, response); }));}
    void SetMessageAllocatorFor_GetMsg(
        ::grpc::MessageAllocator< ::MsgRequest, ::MsgResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::MsgRequest, ::MsgResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMsg(::grpc::ServerContext* /*context*/, const ::MsgRequest* /*request*/, ::MsgResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetMsg(
      ::grpc::CallbackServerContext* /*context*/, const ::MsgRequest* /*request*/, ::MsgResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetMsg<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetMsg() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMsg(::grpc::ServerContext* /*context*/, const ::MsgRequest* /*request*/, ::MsgResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetMsg() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMsg(::grpc::ServerContext* /*context*/, const ::MsgRequest* /*request*/, ::MsgResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetMsg(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetMsg() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetMsg(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMsg(::grpc::ServerContext* /*context*/, const ::MsgRequest* /*request*/, ::MsgResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetMsg(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetMsg() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::MsgRequest, ::MsgResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::MsgRequest, ::MsgResponse>* streamer) {
                       return this->StreamedGetMsg(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetMsg(::grpc::ServerContext* /*context*/, const ::MsgRequest* /*request*/, ::MsgResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetMsg(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::MsgRequest,::MsgResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetMsg<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetMsg<Service > StreamedService;
};


#endif  // GRPC_msg_2eproto__INCLUDED
