// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: msg.proto

#include "msg.pb.h"
#include "msg.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* MsgService_method_names[] = {
  "/MsgService/GetMsg",
};

std::unique_ptr< MsgService::Stub> MsgService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MsgService::Stub> stub(new MsgService::Stub(channel, options));
  return stub;
}

MsgService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetMsg_(MsgService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MsgService::Stub::GetMsg(::grpc::ClientContext* context, const ::MsgRequest& request, ::MsgResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::MsgRequest, ::MsgResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetMsg_, context, request, response);
}

void MsgService::Stub::async::GetMsg(::grpc::ClientContext* context, const ::MsgRequest* request, ::MsgResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::MsgRequest, ::MsgResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMsg_, context, request, response, std::move(f));
}

void MsgService::Stub::async::GetMsg(::grpc::ClientContext* context, const ::MsgRequest* request, ::MsgResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMsg_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::MsgResponse>* MsgService::Stub::PrepareAsyncGetMsgRaw(::grpc::ClientContext* context, const ::MsgRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::MsgResponse, ::MsgRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetMsg_, context, request);
}

::grpc::ClientAsyncResponseReader< ::MsgResponse>* MsgService::Stub::AsyncGetMsgRaw(::grpc::ClientContext* context, const ::MsgRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetMsgRaw(context, request, cq);
  result->StartCall();
  return result;
}

MsgService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MsgService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MsgService::Service, ::MsgRequest, ::MsgResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MsgService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::MsgRequest* req,
             ::MsgResponse* resp) {
               return service->GetMsg(ctx, req, resp);
             }, this)));
}

MsgService::Service::~Service() {
}

::grpc::Status MsgService::Service::GetMsg(::grpc::ServerContext* context, const ::MsgRequest* request, ::MsgResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


